CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'OPERATOR',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forms (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  template_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by BIGINT REFERENCES users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS markers (
  id BIGSERIAL PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'SQUARE',
  x INTEGER NOT NULL DEFAULT 0,
  y INTEGER NOT NULL DEFAULT 0,
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fields (
  id BIGSERIAL PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  data_type TEXT NOT NULL DEFAULT 'text',
  required BOOLEAN NOT NULL DEFAULT TRUE,
  allowed_chars TEXT NOT NULL DEFAULT '',
  validation_rule JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (form_id, code)
);

CREATE TABLE IF NOT EXISTS cells (
  id BIGSERIAL PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  field_id BIGINT NOT NULL REFERENCES fields (id) ON DELETE CASCADE,
  x INTEGER NOT NULL DEFAULT 0,
  y INTEGER NOT NULL DEFAULT 0,
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  position_x INTEGER NOT NULL DEFAULT 0,
  position_y INTEGER NOT NULL DEFAULT 0,
  expected_value TEXT
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGSERIAL PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms (id) ON DELETE RESTRICT,
  filename TEXT NOT NULL,
  original_name TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'NEW',
  created_by BIGINT REFERENCES users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recognition_jobs (
  id BIGSERIAL PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'NEW',
  worker_id TEXT,
  created_by BIGINT REFERENCES users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recognition_cells (
  id BIGSERIAL PRIMARY KEY,
  recognition_job_id BIGINT NOT NULL REFERENCES recognition_jobs (id) ON DELETE CASCADE,
  form_cell_id BIGINT NOT NULL REFERENCES cells (id) ON DELETE CASCADE,
  recognized_value TEXT,
  candidate_values JSONB NOT NULL DEFAULT '[]'::JSONB,
  confidence NUMERIC(5,4),
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS batches (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'NEW',
  created_by BIGINT REFERENCES users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS batch_documents (
  batch_id BIGINT NOT NULL REFERENCES batches (id) ON DELETE CASCADE,
  document_id BIGINT NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
  PRIMARY KEY (batch_id, document_id)
);

CREATE TABLE IF NOT EXISTS operator_actions (
  id BIGSERIAL PRIMARY KEY,
  recognition_job_id BIGINT NOT NULL REFERENCES recognition_jobs (id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users (id),
  action TEXT NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS character_samples (
  id BIGSERIAL PRIMARY KEY,
  form_id BIGINT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  field_id BIGINT REFERENCES fields (id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  confidence INT DEFAULT 0,
  image_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

